version: "3"

services:
  menu_service:
    image: "restaurant/menu-service"
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db_menu
  mongo_db_menu:
    image: "mongo:5.0"
    restart: always
    ports:
      - 27017:27017
