version: "3"

services:
  menu-service:
    image: "nestjs-restaurant/dining-service"
    restart: always
    ports:
      - 3001:3000
    depends_on:
      - mongo_db_dining
    networks:
      - nestjs-restaurant-network
  mongo_db_dining:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - 27019:27017
    networks:
      - nestjs-restaurant-network
networks:
  nestjs-restaurant-network:
    driver: bridge
